{% set name = "anugased-rectangular" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/csdms-contrib/anuga_BMI

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - cython
    - anuga
    - scipy
  run:
    - anuga
    - pyyaml
    - basic-modeling-interface
    - scipy

test:

about:
  home: https://csdms.colorado.edu/wiki/Model:Anuga
  license: GPLv2
  summary:
    AnugaSedRectangular allows for limited use of ANUGA, a
    hydrodynamic model for simulating depth-averaged flows over 2D
    surfaces, and the sediment transport and vegetation drag modules
    of anugaSed. Use this component for simulations on rectangular
    domains.
  dev_url: https://github.com/GeoscienceAustralia/anuga_core
